name: ðŸš€ Deploy to Server

on:
  push:
    branches:
      - feature/ipg-integration  # Trigger only on push to 'production' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¦ Checkout code
      uses: actions/checkout@v3

    - name: ðŸ” Setup SSH Agent
      run: |
        # Start the SSH agent
        eval "$(ssh-agent -s)"

        # Add SSH private key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

        # Provide the passphrase for the SSH key
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add -p

        # Make sure the known hosts file is present
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: ðŸšš Deploy using rsync
      run: |
        rsync -avz --delete ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
